/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import EDD.GraphP;
import javax.swing.JOptionPane;

/**
 *
 * @author Mafer
 */
public class EditEdge extends javax.swing.JFrame {
    //Atributos de la clase
    private static GraphP graph;
    private static String filePath;
    private static int option;
    static final int ADD_OPTION = 1;
    static final int REMOVE_OPTION = 0;
    
    /**
     * Constructor de la clase EditEdge
     * @param graph grafo
     * @param filePath ruta del archivo
     * @param option si option == 1 se agrega la arista, si option == 0 se elimina la arista
     */
    public EditEdge(GraphP graph, String filePath, int option) {
        initComponents();
        this.graph = graph;
        this.filePath = filePath;
        this.option = option;
        setLocationRelativeTo(null);
    }
    
    /**
     * Agrega una arista al grafo apartir de los valores introducidos en los textField
     */
    public void addEdge(){
        try{
            String strIdA = inputCity1.getText();
            String strIdB = inputCity2.getText();
            String strDistance = inputDistance.getText();

            if(strIdA.isBlank() || strIdB.isBlank() || strDistance.isBlank()){
                JOptionPane.showMessageDialog(null, "Error: ingrese todos los datos del formulario");
            }
            else{
                int idA = Integer.parseInt(strIdA);
                int idB = Integer.parseInt(strIdB);
                double size = Double.parseDouble(strDistance);

                if(!graph.isEdge(idA, idB, size)){
                    graph.addEdge(idA, idB, size);                    
                    JOptionPane.showMessageDialog(null, "Relacion agregada con exito");
                    MainScreen ms = new MainScreen(graph, filePath);
                    this.dispose();
                    ms.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "La relacion existe, no se puede agregar");    
                }
            }                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: dato ingresado no valido");
        }        
    }
    
    /**
     * Elimina una arista al grafo apartir de los valores introducidos en los textField
     */
    public void removeEdge(){
        try{
            String strIdA = inputCity1.getText();
            String strIdB = inputCity2.getText();
            String strDistance = inputDistance.getText();

            if(strIdA.isBlank() || strIdB.isBlank() || strDistance.isBlank()){
                JOptionPane.showMessageDialog(null, "Error: ingrese todos los datos del formulario");
            }
            else{
                int idA = Integer.parseInt(strIdA);
                int idB = Integer.parseInt(strIdB);
                double size = Double.parseDouble(strDistance);
                
                if(graph.isEdge(idA, idB, size)){
                    graph.removeEdge(idA, idB, size);                    
                    JOptionPane.showMessageDialog(null, "Relacion eliminada con exito");
                    MainScreen ms = new MainScreen(graph, filePath);
                    this.dispose();
                    ms.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "La relacion no existe, no se puede eliminar");    
                }
            }                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: dato ingresado no valido");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputCity1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputCity2 = new javax.swing.JTextField();
        inputDistance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        acept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 235, 248));

        jLabel1.setText("ciudad 1");

        jLabel2.setText("ciudad 2");

        jLabel3.setText("distancia");

        cancel.setBackground(java.awt.SystemColor.activeCaption);
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        acept.setBackground(java.awt.SystemColor.activeCaption);
        acept.setForeground(new java.awt.Color(255, 255, 255));
        acept.setText("Aceptar");
        acept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDistance)
                            .addComponent(inputCity2)
                            .addComponent(inputCity1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(acept, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputCity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(acept))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Metodo para eliminar o agregar vertice
    private void aceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptActionPerformed
        // TODO add your handling code here:
        if(this.option == 1){
            addEdge(); 
        }
        else if(this.option == 0){
            removeEdge();
        }
    }//GEN-LAST:event_aceptActionPerformed
    
    //Metodo para regresar a la ventana principal
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainScreen ms = new MainScreen(graph, filePath);
        ms.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEdge(graph, filePath, option).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acept;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField inputCity1;
    private javax.swing.JTextField inputCity2;
    private javax.swing.JTextField inputDistance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
